// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoWeiT.Optimizer.Persistence.History.Data;

#nullable disable

namespace SoWeiT.Optimizer.Persistence.History.Migrations
{
    [DbContext(typeof(OptimizerHistoryDbContext))]
    [Migration("20260310091736_RemoveCumulativeEnergyFromRequestUsers")]
    partial class RemoveCumulativeEnergyFromRequestUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoWeiT.Optimizer.Persistence.History.Data.CustomerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Persistence.History.Data.OptimizerRequestEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AvailablePvPowerWatt")
                        .HasColumnType("double precision");

                    b.Property<double?>("ConsumedPowerWatt")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RequestTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<double?>("TotalRequiredPowerWatt")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RequestTimestamp");

                    b.HasIndex("SessionId");

                    b.ToTable("optimizer_requests", (string)null);
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Persistence.History.Data.OptimizerRequestUserEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<double?>("FairnessFactor")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsSwitchAllowed")
                        .HasColumnType("boolean");

                    b.Property<long>("RequestEntryId")
                        .HasColumnType("bigint");

                    b.Property<double>("RequiredPowerWatt")
                        .HasColumnType("double precision");

                    b.Property<bool?>("ShouldSwitch")
                        .HasColumnType("boolean");

                    b.Property<double?>("SwitchBudget")
                        .HasColumnType("double precision");

                    b.Property<int>("UserIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RequestEntryId");

                    b.HasIndex("RequestEntryId", "UserIndex")
                        .IsUnique();

                    b.ToTable("optimizer_request_users", (string)null);
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Persistence.History.Data.OptimizerSessionEntry", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("N")
                        .HasColumnType("integer");

                    b.Property<int>("Sperrzeit1")
                        .HasColumnType("integer");

                    b.Property<int>("Sperrzeit2")
                        .HasColumnType("integer");

                    b.Property<bool>("UseGreedyFallback")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseOrTools")
                        .HasColumnType("boolean");

                    b.HasKey("SessionId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EndedAtUtc");

                    b.ToTable("optimizer_sessions", (string)null);
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Persistence.History.Data.OptimizerRequestEntry", b =>
                {
                    b.HasOne("SoWeiT.Optimizer.Persistence.History.Data.OptimizerSessionEntry", "Session")
                        .WithMany("Requests")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Persistence.History.Data.OptimizerRequestUserEntry", b =>
                {
                    b.HasOne("SoWeiT.Optimizer.Persistence.History.Data.CustomerEntry", "Customer")
                        .WithMany("RequestUsers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoWeiT.Optimizer.Persistence.History.Data.OptimizerRequestEntry", "Request")
                        .WithMany("Users")
                        .HasForeignKey("RequestEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Persistence.History.Data.CustomerEntry", b =>
                {
                    b.Navigation("RequestUsers");
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Persistence.History.Data.OptimizerRequestEntry", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Persistence.History.Data.OptimizerSessionEntry", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
