// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoWeiT.Optimizer.Api.Data;

#nullable disable

namespace SoWeiT.Optimizer.Api.Migrations
{
    [DbContext(typeof(OptimizerHistoryDbContext))]
    partial class OptimizerHistoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoWeiT.Optimizer.Api.Data.OptimizerRequestEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AvailablePvPowerWatt")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RequestTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestTimestamp");

                    b.HasIndex("SessionId");

                    b.ToTable("optimizer_requests", (string)null);
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Api.Data.OptimizerRequestUserEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsSwitchAllowed")
                        .HasColumnType("boolean");

                    b.Property<long>("RequestEntryId")
                        .HasColumnType("bigint");

                    b.Property<double>("RequiredPowerWatt")
                        .HasColumnType("double precision");

                    b.Property<int>("UserIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequestEntryId");

                    b.HasIndex("RequestEntryId", "UserIndex")
                        .IsUnique();

                    b.ToTable("optimizer_request_users", (string)null);
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Api.Data.OptimizerSessionEntry", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("N")
                        .HasColumnType("integer");

                    b.Property<int>("Sperrzeit1")
                        .HasColumnType("integer");

                    b.Property<int>("Sperrzeit2")
                        .HasColumnType("integer");

                    b.Property<bool>("UseGreedyFallback")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseOrTools")
                        .HasColumnType("boolean");

                    b.HasKey("SessionId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EndedAtUtc");

                    b.ToTable("optimizer_sessions", (string)null);
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Api.Data.OptimizerRequestEntry", b =>
                {
                    b.HasOne("SoWeiT.Optimizer.Api.Data.OptimizerSessionEntry", "Session")
                        .WithMany("Requests")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Api.Data.OptimizerRequestUserEntry", b =>
                {
                    b.HasOne("SoWeiT.Optimizer.Api.Data.OptimizerRequestEntry", "Request")
                        .WithMany("Users")
                        .HasForeignKey("RequestEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Api.Data.OptimizerRequestEntry", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SoWeiT.Optimizer.Api.Data.OptimizerSessionEntry", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
