using Microsoft.EntityFrameworkCore;
using Serilog;
using SoWeiT.Optimizer.Api.Data;
using SoWeiT.Optimizer.Api.Persistence;
using SoWeiT.Optimizer.Api.Services;
using StackExchange.Redis;

var builder = WebApplication.CreateBuilder(args);

Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(builder.Configuration)
    .Enrich.FromLogContext()
    .WriteTo.Console()
    .CreateLogger();

builder.Host.UseSerilog();

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddSingleton<OptimizerSessionService>();
builder.Services.AddSingleton<IConnectionMultiplexer>(_ =>
{
    var redisConnectionString = builder.Configuration.GetConnectionString("Redis")
                                ?? throw new InvalidOperationException("ConnectionStrings:Redis is missing.");
    return ConnectionMultiplexer.Connect(redisConnectionString);
});
builder.Services.AddSingleton<IOptimizerStateStore, RedisOptimizerStateStore>();
builder.Services.AddDbContextFactory<OptimizerHistoryDbContext>(options =>
{
    var postgresConnectionString = builder.Configuration.GetConnectionString("Postgres")
                                   ?? throw new InvalidOperationException("ConnectionStrings:Postgres is missing.");
    options.UseNpgsql(postgresConnectionString);
});
builder.Services.AddSingleton<IOptimizerUnitOfWorkFactory, EfCoreOptimizerUnitOfWorkFactory>();
builder.Services.AddSingleton<IOptimizerHistoryStore, EfCoreOptimizerHistoryStore>();

var app = builder.Build();

app.UseSerilogRequestLogging();


    app.UseSwagger();
    app.UseSwaggerUI();


app.UseHttpsRedirection();
app.MapControllers();

using (var scope = app.Services.CreateScope())
{
    var dbFactory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<OptimizerHistoryDbContext>>();
    using var dbContext = dbFactory.CreateDbContext();
    dbContext.Database.EnsureCreated();

    dbContext.Database.ExecuteSqlRaw("""
                                     CREATE TABLE IF NOT EXISTS optimizer_sessions (
                                         session_id uuid PRIMARY KEY,
                                         created_at_utc timestamp without time zone NOT NULL,
                                         ended_at_utc timestamp without time zone NULL,
                                         n integer NOT NULL,
                                         sperrzeit1 integer NOT NULL,
                                         sperrzeit2 integer NOT NULL,
                                         use_or_tools boolean NOT NULL,
                                         use_greedy_fallback boolean NOT NULL
                                     );
                                     """);

    dbContext.Database.ExecuteSqlRaw("""
                                     CREATE TABLE IF NOT EXISTS optimizer_requests (
                                         id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         session_id uuid NOT NULL REFERENCES optimizer_sessions(session_id) ON DELETE CASCADE,
                                         request_type character varying(128) NOT NULL,
                                         request_timestamp timestamp with time zone NOT NULL,
                                         created_at_utc timestamp without time zone NOT NULL,
                                         available_pv_power_watt double precision NULL
                                     );
                                     """);

    dbContext.Database.ExecuteSqlRaw("""
                                     CREATE TABLE IF NOT EXISTS optimizer_request_users (
                                         id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         request_entry_id bigint NOT NULL REFERENCES optimizer_requests(id) ON DELETE CASCADE,
                                         user_index integer NOT NULL,
                                         required_power_watt double precision NOT NULL,
                                         is_switch_allowed boolean NOT NULL
                                     );
                                     """);

    dbContext.Database.ExecuteSqlRaw("""
                                     CREATE INDEX IF NOT EXISTS ix_optimizer_sessions_created_at_utc
                                     ON optimizer_sessions (created_at_utc);
                                     """);

    dbContext.Database.ExecuteSqlRaw("""
                                     CREATE INDEX IF NOT EXISTS ix_optimizer_sessions_ended_at_utc
                                     ON optimizer_sessions (ended_at_utc);
                                     """);

    dbContext.Database.ExecuteSqlRaw("""
                                     CREATE INDEX IF NOT EXISTS ix_optimizer_requests_session_id
                                     ON optimizer_requests (session_id);
                                     """);

    dbContext.Database.ExecuteSqlRaw("""
                                     CREATE INDEX IF NOT EXISTS ix_optimizer_requests_request_timestamp
                                     ON optimizer_requests (request_timestamp);
                                     """);

    dbContext.Database.ExecuteSqlRaw("""
                                     CREATE INDEX IF NOT EXISTS ix_optimizer_request_users_request_entry_id
                                     ON optimizer_request_users (request_entry_id);
                                     """);

    dbContext.Database.ExecuteSqlRaw("""
                                     CREATE UNIQUE INDEX IF NOT EXISTS ix_optimizer_request_users_request_entry_id_user_index
                                     ON optimizer_request_users (request_entry_id, user_index);
                                     """);

    try
    {
        dbContext.Database.ExecuteSqlRaw("""
                                         CREATE EXTENSION IF NOT EXISTS timescaledb;
                                         SELECT create_hypertable('optimizer_requests', 'request_timestamp', if_not_exists => TRUE, migrate_data => TRUE);
                                         """);
    }
    catch
    {
        // TimescaleDB extension is optional in local/dev environments.
    }
}

app.Run();
